---
http_interactions:
- request:
    method: post
    uri: unix:///var/run/docker.sock/v1.9/containers/create
    body:
      encoding: UTF-8
      string: '{"Cmd":["true"],"Image":"base"}'
    headers:
      User-Agent:
      - Swipely/Docker-API 1.7.6
      Content-Type:
      - application/json
  response:
    status:
      code: 201
      message: 
    headers:
      Content-Type:
      - application/json
      Date:
      - Sat, 08 Feb 2014 15:26:35 GMT
      Content-Length:
      - '90'
      Connection:
      - close
    body:
      encoding: UTF-8
      string: |
        {"Id":"638fd7f22b8ba8a3a74dedb7cdbf23e2c297c0157b4996648f54a110eabc4566","Warnings":null}
    http_version: 
  recorded_at: Sat, 08 Feb 2014 15:26:35 GMT
- request:
    method: post
    uri: unix:///var/run/docker.sock/v1.9/commit?container=638fd7f2
    body:
      encoding: UTF-8
      string: '{"Cmd":["pwd"]}'
    headers:
      User-Agent:
      - Swipely/Docker-API 1.7.6
      Content-Type:
      - application/json
  response:
    status:
      code: 201
      message: 
    headers:
      Content-Type:
      - application/json
      Date:
      - Sat, 08 Feb 2014 15:26:37 GMT
      Content-Length:
      - '74'
      Connection:
      - close
    body:
      encoding: UTF-8
      string: |
        {"Id":"523fbca8f2bf590bdde35a7ea16384f316ae768a3898b83b9e500a5749e51945"}
    http_version: 
  recorded_at: Sat, 08 Feb 2014 15:26:37 GMT
- request:
    method: post
    uri: unix:///var/run/docker.sock/v1.9/containers/create
    body:
      encoding: UTF-8
      string: '{"Image":"523fbca8f2bf590bdde35a7ea16384f316ae768a3898b83b9e500a5749e51945","Cmd":null}'
    headers:
      User-Agent:
      - Swipely/Docker-API 1.7.6
      Content-Type:
      - application/json
  response:
    status:
      code: 500
      message: 
    headers:
      Content-Type:
      - text/plain; charset=utf-8
      Date:
      - Sat, 08 Feb 2014 15:26:37 GMT
      Content-Length:
      - '29'
      Connection:
      - close
    body:
      encoding: UTF-8
      string: |
        create: No command specified
    http_version: 
  recorded_at: Sat, 08 Feb 2014 15:26:37 GMT
recorded_with: VCR 2.8.0
