---
http_interactions:
- request:
    method: post
    uri: unix:///var/run/docker.sock/v1.9/containers/create
    body:
      encoding: UTF-8
      string: "{\"Cmd\":[\"true\"],\"Image\":\"ubuntu\"}"
    headers:
      User-Agent:
      - Swipely/Docker-API 1.7.6
      Content-Type:
      - application/json
  response:
    status:
      code: 201
      message: 
    headers:
      Content-Type:
      - application/json
      Date:
      - Sun, 09 Feb 2014 16:12:02 GMT
      Content-Length:
      - '90'
      Connection:
      - close
    body:
      encoding: UTF-8
      string: |
        {"Id":"52808fbf297dcf2998b39d0a4a33dca6809a74782d2c9c2f87a4bf5a2cd31560","Warnings":null}
    http_version: 
  recorded_at: Sun, 09 Feb 2014 16:12:02 GMT
- request:
    method: post
    uri: unix:///var/run/docker.sock/v1.9/commit?container=52808fbf
    body:
      encoding: UTF-8
      string: "{\"Cmd\":[\"/bin/pwd\"]}"
    headers:
      User-Agent:
      - Swipely/Docker-API 1.7.6
      Content-Type:
      - application/json
  response:
    status:
      code: 201
      message: 
    headers:
      Content-Type:
      - application/json
      Date:
      - Sun, 09 Feb 2014 16:12:02 GMT
      Content-Length:
      - '74'
      Connection:
      - close
    body:
      encoding: UTF-8
      string: |
        {"Id":"233e5f1c6d942e82730f90a3a6d5c23803b0f59422c89ce6850c39fe541da008"}
    http_version: 
  recorded_at: Sun, 09 Feb 2014 16:12:02 GMT
- request:
    method: post
    uri: unix:///var/run/docker.sock/v1.9/containers/create
    body:
      encoding: UTF-8
      string: "{\"Image\":\"233e5f1c6d942e82730f90a3a6d5c23803b0f59422c89ce6850c39fe541da008\",\"Cmd\":null}"
    headers:
      User-Agent:
      - Swipely/Docker-API 1.7.6
      Content-Type:
      - application/json
  response:
    status:
      code: 500
      message: 
    headers:
      Content-Type:
      - text/plain; charset=utf-8
      Date:
      - Sun, 09 Feb 2014 16:12:02 GMT
      Content-Length:
      - '29'
      Connection:
      - close
    body:
      encoding: UTF-8
      string: |
        create: No command specified
    http_version: 
  recorded_at: Sun, 09 Feb 2014 16:12:02 GMT
recorded_with: VCR 2.8.0
